kick-message: "lang:multiplayer.disconnect.idling"
afk-time: 300 # in seconds
check-interval: 10 # in seconds
check:
  blocks: true
  move: true
  orientation: true
  sneaking: false
  jumping: false
  interact: true
  inventory: true
  fishing: true
  commands: true
  chat : true